version: '3.8'

services:
  backend1:
    build:
      context: ./backend
    container_name: backend1
    expose:
     - 3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend2:
    build:
      context: ./backend
    container_name: backend2
    expose:
      - 3001

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend1
      - backend2
